spring.application.name=foodbillpro

# Server
server.port=8080

# MySQL Database
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${JDBC_NAME}
spring.datasource.password=${JDBC_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Upload folder path
app.upload.dir=uploads

# JWT
app.jwt.secret=${JWT_KEY}
app.jwt.expiration=86400000

# Admin credentials
app.admin.username=${ADMIN_NAME}
app.admin.password=${ADMIN_PASSWORD}

# CORS
app.cors.allowed-origins=http://localhost:5173